/*
 * File: app/view/grids/GameGrid.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.grids.GameGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grids.gamegrid',

    requires: [
        'Enif.view.grids.GameGridViewModel',
        'Enif.view.grids.GameGridViewController',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.plugin.RowOperations',
        'Ext.grid.plugin.CellEditing',
        'Ext.Toolbar',
        'Ext.field.ComboBox',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.SegmentedButton'
    ],

    controller: 'grids.gamegrid',
    viewModel: {
        type: 'grids.gamegrid'
    },
    height: '100%',
    name: 'grids.GameGrid',
    width: '100%',
    maxWidth: 1000,
    minWidth: 900,
    selectable: {
        mode: 'single',
        checkbox: true
    },
    store: 'GameRawData',
    striped: false,

    columns: [
        {
            xtype: 'rownumberer',
            width: 50
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {
                return Ext.Date.format(new Date(value), 'd.m.Y');
            },
            align: 'center',
            dataIndex: 'timestamp',
            text: 'Timestamp'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            width: 160,
            align: 'center',
            dataIndex: 'timestamp',
            text: 'Time-ID'
        },
        {
            xtype: 'numbercolumn',
            width: 158,
            align: 'center',
            dataIndex: 'playerWhiteRating',
            text: 'Player White Rating',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {

                cell.setCls('white_cell');
                return this.up('grid').getController().getUserName(value);

            },
            align: 'center',
            dataIndex: 'playerWhite',
            text: 'Player White'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {
                cell.setCls('black_cell');
                return this.up('grid').getController().getUserName(value);
            },
            align: 'center',
            dataIndex: 'playerBlack',
            text: 'Player Black'
        },
        {
            xtype: 'numbercolumn',
            width: 145,
            align: 'center',
            dataIndex: 'playerBlackRating',
            text: 'Player Black Rating',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {
                let name = value;

                if(value == "white"){
                    name = this.up('grid').getController().getUserName(record.getData().playerWhite);
                    cell.setCls('white_cell');
                }else if (value == "black") {
                    name = this.up('grid').getController().getUserName(record.getData().playerBlack);
                    cell.setCls('black_cell');
                }else if (value == 'draw'){
                    name = "draw";
                }

                return name;
            },
            align: 'center',
            dataIndex: 'result',
            text: 'Won'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {
                if (value === false){
                    return "No";
                }else{
                    return "Yes";
                }
            },
            align: 'center',
            dataIndex: 'timeout',
            text: 'Timeout'
        }
    ],
    plugins: [
        {
            type: 'rowoperations'
        },
        {
            type: 'gridcellediting'
        }
    ],
    items: [
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'combobox',
                    name: 'playerFilter',
                    label: 'Filter by player',
                    editable: false,
                    displayField: 'name',
                    store: 'PlayerData',
                    valueField: 'uid',
                    queryMode: 'local',
                    listeners: {
                        change: 'onFilterPlayerChange'
                    }
                },
                {
                    xtype: 'combobox',
                    name: 'resultFilter',
                    width: 136,
                    margin: '0 10 0 5',
                    label: 'result',
                    labelWidth: 50,
                    value: 'none',
                    editable: false,
                    options: [
                        {
                            text: 'Either',
                            value: 'none'
                        },
                        {
                            text: 'Won',
                            value: 'won'
                        },
                        {
                            text: 'Lost',
                            value: 'lost'
                        }
                    ],
                    queryMode: 'local',
                    listeners: {
                        change: 'onFilterResultChange'
                    }
                },
                {
                    xtype: 'button',
                    tooltip: 'Clear the filters',
                    iconCls: 'x-fa fa-close',
                    text: 'Clear',
                    listeners: {
                        tap: 'onClearFilterTap'
                    }
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    reference: 'unlockButton',
                    iconCls: 'x-fa fa-unlock-alt',
                    text: 'Unlock',
                    listeners: {
                        tap: 'onUnlockButtonTap'
                    }
                },
                {
                    xtype: 'segmentedbutton',
                    allowToggle: false,
                    items: [
                        {
                            xtype: 'button',
                            reference: 'moveUp',
                            disabled: true,
                            tooltip: 'Move Selected Record Up',
                            iconCls: 'x-fa fa-arrow-up',
                            text: 'Move UP',
                            listeners: {
                                tap: 'onMoveUpButtonTap'
                            }
                        },
                        {
                            xtype: 'button',
                            reference: 'moveDown',
                            disabled: true,
                            tooltip: 'Move selected record down',
                            iconCls: 'x-fa fa-arrow-down',
                            text: 'Move DOWN',
                            listeners: {
                                tap: 'onMoveDownButtonTap'
                            }
                        }
                    ]
                },
                {
                    xtype: 'button',
                    reference: 'moveSave',
                    disabled: true,
                    tooltip: 'Save move changes',
                    iconCls: 'x-fa fa-check',
                    text: 'Save',
                    listeners: {
                        tap: 'onSaveMoveButtonTap'
                    }
                }
            ]
        }
    ]

});