/*
 * File: app/view/grids/GameGridViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.grids.GameGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.grids.gamegrid',

    getUserName: function(value) {
        let store = Ext.getStore('PlayerData'),
            recordPos = store.find('uid', value),
            rc = store.getAt(recordPos);

        if(rc){
            return rc.get('name');
        } else {
            console.error("Did not found ", value);
            return "Error";
        }
    }

});