/*
 * File: app/view/grids/GameGridViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.grids.GameGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.grids.gamegrid',

    getUserName: function(value) {
        let store = Ext.getStore('PlayerData'),
            recordPos = store.find('uid', value),
            rc = store.getAt(recordPos);

        if(rc){
            return rc.get('name');
        } else {
            console.error("Did not found ", value);
            return "Error";
        }
    },

    /* Result option: won, lost, none */
    filterStore: function(player, filterResult) {
        let gridStore = this.getView().getStore(),
            selectedPlayer = player,
            selectedResult = filterResult;


        // clear any filtering on the Store
        gridStore.clearFilter();

        gridStore.filterBy(function(rec) {

            let playerWhite = rec.get('playerWhite'),
                playerBlack = rec.get('playerBlack'),
                result = rec.get('result');


            if(playerWhite === selectedPlayer || playerBlack === selectedPlayer) {

                if(selectedResult == 'none'){
                    return true;
                }

                if( playerWhite === selectedPlayer && result == 'white' && selectedResult == 'won') {
                    return true;
                }

                if ( playerBlack ===  selectedPlayer && result == 'black' && selectedResult == 'won') {
                    return true;
                }

                if( playerWhite === selectedPlayer && result == 'black' && selectedResult == 'lost') {
                    return true;
                }

                if ( playerBlack ===  selectedPlayer && result == 'white' && selectedResult == 'lost') {
                    return true;
                }

                return false;
            } else {
                return false;
            }

        });
    },

    /* This function can move the record in the grid up and down by swapping their timestamp */
    moveRecords: function(move) {
        let grid = this.getView();
            selections = grid.getSelections();

        if(!selections) return;

        let selected = selections[0], // we have single selection enabled
            store = grid.getStore(),
            recordPosition = store.indexOf(selected);
            newPosition = null;

        if (move === 'up'){
            newPosition = recordPosition - 1;
        }else if (move === 'down'){
            newPosition = recordPosition + 1;
        }

        if (!newPosition || newPosition < 0 || newPosition > store.getData().getCount() - 1){
            Ext.toast('You can\'t move the record outside of the grid silly', 3000);
            return;
        }


        let swapRecord = store.getAt(newPosition),
            timestamp = swapRecord.get('timestamp');

        swapRecord.set('timestamp', selected.get('timestamp'));
        selected.set('timestamp', timestamp);

        grid.select(newPosition);

        grid.refresh();
        Ext.toast('Record moved', 1000);

    },

    onFilterPlayerChange: function(combobox, newValue, oldValue, eOpts) {
        let selectedPlayer = this.getView().query('combobox[name=playerFilter]')[0].getValue(),
        selectedResult = this.getView().query('combobox[name=resultFilter]')[0].getValue();

        this.filterStore(selectedPlayer, selectedResult);
    },

    onFilterResultChange: function(combobox, newValue, oldValue, eOpts) {
        let selectedPlayer = this.getView().query('combobox[name=playerFilter]')[0].getValue(),
        selectedResult = this.getView().query('combobox[name=resultFilter]')[0].getValue();

        this.filterStore(selectedPlayer, selectedResult);
    },

    onClearFilterTap: function(button, e, eOpts) {
        let selectedPlayerCombo = this.getView().query('combobox[name=playerFilter]')[0], // we can't wipe the player combo
        selectedResultCombo = this.getView().query('combobox[name=resultFilter]')[0];

        // selectedPlayerCombo.clearValue();
        // Error: Clear is not a function - http://docs.sencha.com/extjs/6.5.0/modern/Ext.field.ComboBox.html#method-clearValue
        console.log('Can\'t clear the playerFilter combo - the store filter itself is removed...');
        selectedResultCombo.setValue('none');
        this.getView().getStore().clearFilter();

    },

    onUnlockButtonTap: function(button, e, eOpts) {
        let mvUpBtn = this.lookupReference('moveUp'),
        mvDownBtn = this.lookupReference('moveDown'),
        saveBtn = this.lookupReference('moveSave'),
        unlockButton = this.lookupReference('unlockButton'); // using reference instead of passed argument, so we can call this function elsewhere ("hacks")

        if(mvUpBtn.isDisabled()){
            mvUpBtn.enable();
            mvDownBtn.enable();
            saveBtn.enable();
            unlockButton.setText('Lock');
            unlockButton.setIconCls('x-fa fa-lock');

        }else{
            mvUpBtn.disable();
            mvDownBtn.disable();
            saveBtn.disable();
            unlockButton.setText('Unlock');
            unlockButton.setIconCls('x-fa fa-unlock-alt');
        }
    },

    onMoveUpButtonTap: function(button, e, eOpts) {
        this.moveRecords('up');
    },

    onMoveDownButtonTap: function(button, e, eOpts) {
        this.moveRecords('down');
    },

    onSaveMoveButtonTap: function(button, e, eOpts) {
        this.onUnlockButtonTap();

        //TODO: Fix back-end , this crashesh the node
        console.log('backend not working -- disabled');
        // this.getView().getStore().sync({
        //     callback: function (records, operation, success) {
        //         Enif.app.getController('storeLoadController').reloadAllStores();
        //     },
        //     success: function (batch, options) {
        //         Ext.toast('Record sucesffully moved', 3000);
        //     },
        //     failure: function (batch, options) {
        //         Ext.toast('Error while editing the rows', 3000);
        //     }
        // });
    }

});