/*
 * File: app/view/grids/PlayerGrids.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.grids.PlayerGrids', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grids.playergrids',

    requires: [
        'Ext.grid.column.Number',
        'Ext.grid.cell.Widget'
    ],

    name: 'grids.PlayerGrids',
    width: '100%',
    maxWidth: 1000,
    store: 'PlayerData',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'name',
            text: 'Name'
        },
        {
            xtype: 'numbercolumn',
            width: 59,
            dataIndex: 'rating',
            text: 'Rating',
            format: '0'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'wins',
            text: 'Wins',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 69,
            align: 'center',
            dataIndex: 'loses',
            text: 'Loses',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'draws',
            text: 'Draws',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'games',
            text: 'Games',
            format: '00'
        },
        {
            xtype: 'gridcolumn',
            width: 1,
            cell: {
                xtype: 'widgetcell',
                cellCls: 'custom_line'
            }
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'winsWhite',
            text: 'Wins White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'winsBlack',
            text: 'Wins Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'losesWhite',
            text: 'Loses White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 84,
            align: 'center',
            dataIndex: 'losesBlack',
            text: 'Loses Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'drawWhite',
            text: 'Draw White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'drawBlack',
            text: 'Draw Black',
            format: '00'
        }
    ]

});