/*
 * File: app/view/grids/PlayerGrids.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.grids.PlayerGrids', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grids.playergrids',

    requires: [
        'Enif.view.grids.PlayerGridsViewModel',
        'Ext.grid.column.Number',
        'Ext.grid.cell.Widget',
        'Ext.grid.plugin.Summary',
        'Ext.data.summary.Count',
        'Ext.data.summary.Average',
        'Ext.data.summary.Sum'
    ],

    viewModel: {
        type: 'grids.playergrids'
    },
    height: '100%',
    name: 'grids.PlayerGrids',
    width: '100%',
    maxWidth: 1000,
    store: 'SortedPlayerData',

    columns: [
        {
            xtype: 'numbercolumn',
            hidden: true,
            width: 80,
            dataIndex: 'uid',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'name',
            summary: 'count',
            text: 'Name'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'games',
            summary: 'sum',
            text: 'Games',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'wins',
            text: 'Wins',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 66,
            align: 'center',
            dataIndex: 'draws',
            text: 'Draws',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 69,
            align: 'center',
            dataIndex: 'loses',
            text: 'Loses',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 59,
            dataIndex: 'rating',
            summary: 'average',
            text: 'Rating',
            format: '0'
        },
        {
            xtype: 'numbercolumn',
            hidden: true,
            width: 59,
            dataIndex: 'rating',
            summary: 'average',
            text: 'Full Rating'
        },
        {
            xtype: 'gridcolumn',
            width: 1,
            hideable: false,
            cell: {
                xtype: 'widgetcell',
                cellCls: 'custom_line'
            }
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'winsWhite',
            summary: 'sum',
            text: 'Wins White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'winsBlack',
            summary: 'sum',
            text: 'Wins Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'losesWhite',
            summary: 'sum',
            text: 'Loses White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 84,
            align: 'center',
            dataIndex: 'losesBlack',
            summary: 'sum',
            text: 'Loses Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'drawWhite',
            summary: 'sum',
            text: 'Draw White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            width: 90,
            align: 'center',
            dataIndex: 'drawBlack',
            summary: 'sum',
            text: 'Draw Black',
            format: '00'
        }
    ],
    plugins: [
        {
            type: 'gridsummaryrow'
        }
    ]

});