/*
 * File: app/view/grid/PlayerGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.grid.PlayerGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grid.playergrid',

    requires: [
        'Ext.grid.column.Number'
    ],

    height: 900,
    name: 'grid.PlayerGrid',
    width: '100%',
    store: 'PlayerData',

    columns: [
        {
            xtype: 'numbercolumn',
            hidden: true,
            dataIndex: 'uid',
            text: 'Uid',
            format: '00'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'name',
            text: 'Name'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'games',
            text: 'Games',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'rating',
            text: 'Rating',
            format: '0'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'wins',
            text: 'Wins',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'winsWhite',
            text: 'Wins White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'winsBlack',
            text: 'Wins Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'loses',
            text: 'Loses',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'losesWhite',
            text: 'Loses White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'losesBlack',
            text: 'Loses Black',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'draws',
            text: 'Draws',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'drawWhite',
            text: 'Draw White',
            format: '00'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'drawBlack',
            text: 'Draw Black',
            format: '00'
        }
    ]

});