/*
 * File: app/view/pivot/RoundRobinGrid.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.pivot.RoundRobinGrid', {
    extend: 'Ext.pivot.Grid',
    alias: 'widget.pivot.roundrobingrid',

    requires: [
        'Enif.view.pivot.RoundRobinGridViewModel',
        'Ext.pivot.matrix.Local',
        'Ext.pivot.dimension.Item'
    ],

    viewModel: {
        type: 'pivot.roundrobingrid'
    },
    height: '100%',
    width: '100%',

    matrix: {
        store: 'PlayerData',
        leftAxis: [
            {
                dataIndex: 'name',
                sortIndex: 'uid'
            }
        ],
        topAxis: [
            {
                dataIndex: 'name',
                sortable: false,
                sortIndex: 'uid'
            }
        ],
        aggregate: {
            renderer: function(value, record, dataIndex, cell, column) {
                let cellColumn = parseInt(dataIndex.replace(/\D/g,''));
                let playersStore = Ext.getStore('PlayerData');

                if (cellColumn > playersStore.count() || record.data.isRowGrandTotal) { //aggregate cells
                    cell.setBodyStyle({
                        background: '#025b80'
                    });
                    return;
                }

                let cellRow = playersStore.find('name', record.data["ext-153"])+1;

                if (cellColumn === cellRow) {
                    cell.setBodyStyle({
                        background: '#025b80'
                    });
                    return;
                }

                let wins = 0,
                draws = 0,
                loses = 0;

                let games = Ext.getStore('GameRawData');

                games.clearFilter();
                games.filterBy(function(rec) {
                    if ((rec.get('playerWhite') === cellRow &&
                    rec.get('playerBlack') === cellColumn &&
                    rec.get('result') === 'white') ||
                    (rec.get('playerBlack') === cellRow &&
                    rec.get('playerWhite') === cellColumn &&
                    rec.get('result') === 'black')) {
                        wins++;
                        return true;
                    } else if((rec.get('playerWhite') === cellRow &&
                    rec.get('playerBlack') === cellColumn &&
                    rec.get('result') === 'black') ||
                    (rec.get('playerBlack') === cellRow &&
                    rec.get('playerWhite') === cellColumn &&
                    rec.get('result') === 'white')) {
                        loses++;
                        return true;
                    } else if((rec.get('playerWhite') === cellRow &&
                    rec.get('playerBlack') === cellColumn &&
                    rec.get('result') === 'draw') ||
                    (rec.get('playerBlack') === cellRow &&
                    rec.get('playerWhite') === cellColumn &&
                    rec.get('result') === 'draw')) {
                        draws++;
                        return true;
                    }
                    return false;
                });

                return wins + " : " + draws + " : " + loses + ' (' + games.getCount() + ')';

            },
            dataIndex: 'games'
        }
    }

});