/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'PlayerData',
        'ChartsData'
    ],
    stores: [
        'GameRawData',
        'PlayerData',
        'EloRatinChart',
        'WinsByColor',
        'SortedPlayerData',
        'pivot.HeatMap'
    ],
    views: [
        'grids.PlayerGrids',
        'grids.GameGrid',
        'MainPanel',
        'charts.EloRating',
        'charts.PlayedGames',
        'charts.WinsByColor',
        'Loading',
        'forms.AddGameDialog',
        'forms.AddGameForm',
        'pivot.RoundRobinGrid',
        'MainViewport',
        'charts.EloRatingNavigator',
        'mobile.MainPanel',
        'charts.Ladder',
        'stats',
        'pivot.HeatMap',
        'charts.PlayerVsPlayer'
    ],
    controllers: [
        'StoreLoadController'
    ],
    defaultToken: 'players',
    name: 'Enif',

    requires: [
        'Enif.controller.StoreLoadController'
    ],

    launch: function() {
        Ext.create('Enif.view.MainViewport', {fullscreen: true});
    }

});
