/*
 * File: app/view/forms/AddGameForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    Added Ext.Toast to the requires because we are using it in the viewcontroller
*/
Ext.define('Enif.view.forms.AddGameForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.forms.addgameform',

    requires: [
        'Enif.view.forms.AddGameFormViewModel',
        'Enif.view.forms.AddGameFormViewController',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.form.FieldSet',
        'Ext.field.ComboBox',
        'Ext.field.Container',
        'Ext.SegmentedButton',
        'Ext.Button',
        'Ext.Toast'
    ],

    controller: 'forms.addgameform',
    viewModel: {
        type: 'forms.addgameform'
    },
    itemId: 'addForm',
    maxWidth: 600,
    header: false,
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'datefield',
            id: 'timestampPicker',
            name: 'timestamp',
            margin: 10,
            label: 'Date of match',
            value: new Date(),
            picker: {
                xtype: 'datepicker',
                title: 'My Panel'
            }
        },
        {
            xtype: 'fieldset',
            id: 'players_fieldset',
            layout: 'hbox',
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    itemId: 'mycombobox',
                    name: 'playerWhite',
                    margin: '0 10 0 0',
                    modelValidation: true,
                    label: 'White Player',
                    editable: false,
                    displayField: 'name',
                    store: 'PlayerData',
                    valueField: 'uid',
                    queryMode: 'local',
                    listeners: {
                        change: 'onMycomboboxChange'
                    }
                },
                {
                    xtype: 'combobox',
                    flex: 1,
                    itemId: 'mycombobox1',
                    name: 'playerBlack',
                    margin: '0 0 0 10',
                    modelValidation: true,
                    label: 'Black Player',
                    editable: false,
                    displayField: 'name',
                    store: 'PlayerData',
                    valueField: 'uid',
                    queryMode: 'local',
                    listeners: {
                        change: 'onMycombobox1Change'
                    }
                }
            ]
        },
        {
            xtype: 'fieldset',
            layout: 'hbox',
            items: [
                {
                    xtype: 'containerfield',
                    flex: 1,
                    margin: '0 10 0 0',
                    label: 'Won',
                    labelMinWidth: 50,
                    items: [
                        {
                            xtype: 'segmentedbutton',
                            name: 'playerWon',
                            maxWidth: 300,
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 2,
                                    name: 'playerWhite',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-user-o',
                                    text: 'White',
                                    value: 'white'
                                },
                                {
                                    xtype: 'button',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-pause',
                                    text: 'Draw',
                                    value: 'draw'
                                },
                                {
                                    xtype: 'button',
                                    flex: 2,
                                    name: 'playerBlack',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-user',
                                    text: 'Black',
                                    value: 'black'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'containerfield',
                    flex: 1,
                    margin: '0 0 0 10',
                    bodyAlign: 'center',
                    label: 'Run out of time',
                    labelMinWidth: 105,
                    items: [
                        {
                            xtype: 'segmentedbutton',
                            height: 50,
                            name: 'time',
                            width: 100,
                            value: 'false',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    pressed: true,
                                    text: 'No',
                                    value: 'false'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    text: 'Yes',
                                    value: 'true'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onMycomboboxChange: function(combobox, newValue, oldValue, eOpts) {
        this.comboChange();
    },

    onMycombobox1Change: function(combobox, newValue, oldValue, eOpts) {
        this.comboChange();
    },

    comboChange: function() {
        let whiteName = this.query('combobox[name=playerWhite]')[0].getSelection();
        let blackName = this.query('combobox[name=playerBlack]')[0].getSelection();

        if (whiteName == blackName && (whiteName != "" && blackName != "") ){
            Ext.toast('Player can\'t play againts himself', 3000);
        }

        whiteName = whiteName ? whiteName.get('name') : "";
        blackName = blackName ? blackName.get('name') : "";

        if(whiteName !== "") this.query('button[name=playerWhite]')[0].setText(whiteName);
        if(blackName !== "") this.query('button[name=playerBlack]')[0].setText(blackName);
    }

});