/*
 * File: app/view/forms/AddGameForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    Added Ext.Toast to the requires because we are using it in the viewcontroller
*/
Ext.define('Enif.view.forms.AddGameForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.forms.addgameform',

    requires: [
        'Enif.view.forms.AddGameFormViewModel',
        'Enif.view.forms.AddGameFormViewController',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.form.FieldSet',
        'Ext.field.ComboBox',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Container',
        'Ext.SegmentedButton',
        'Ext.Toast'
    ],

    controller: 'forms.addgameform',
    viewModel: {
        type: 'forms.addgameform'
    },
    itemId: 'addForm',
    width: '100%',
    header: false,
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'datefield',
            id: 'timestampPicker',
            name: 'timestamp',
            margin: 10,
            label: 'Date of match',
            value: new Date(),
            picker: {
                xtype: 'datepicker',
                title: 'Date of Game',
                titleAlign: 'center'
            }
        },
        {
            xtype: 'fieldset',
            platformConfig: {
                phone: {
                    layout: 'vbox'
                },
                '!phone': {
                    layout: 'hbox'
                }
            },
            id: 'players_fieldset',
            layout: 'hbox',
            items: [
                {
                    xtype: 'combobox',
                    flex: 8,
                    itemId: 'mycombobox',
                    name: 'playerWhite',
                    modelValidation: true,
                    label: 'White Player',
                    editable: false,
                    displayField: 'name',
                    store: 'PlayerData',
                    valueField: 'uid',
                    queryMode: 'local',
                    listeners: {
                        change: 'onMycomboboxChange'
                    }
                },
                {
                    xtype: 'spacer',
                    flex: 1
                },
                {
                    xtype: 'button',
                    flex: 1,
                    itemId: 'mybutton11',
                    iconCls: 'x-fa fa-exchange',
                    text: '',
                    listeners: {
                        tap: 'onMybutton11Tap'
                    }
                },
                {
                    xtype: 'spacer',
                    flex: 1
                },
                {
                    xtype: 'combobox',
                    flex: 8,
                    itemId: 'mycombobox1',
                    name: 'playerBlack',
                    modelValidation: true,
                    label: 'Black Player',
                    editable: false,
                    displayField: 'name',
                    store: 'PlayerData',
                    valueField: 'uid',
                    queryMode: 'local',
                    listeners: {
                        change: 'onMycombobox1Change'
                    }
                }
            ]
        },
        {
            xtype: 'fieldset',
            platformConfig: {
                phone: {
                    layout: 'vbox'
                },
                '!phone': {
                    layout: 'hbox'
                }
            },
            layout: 'hbox',
            items: [
                {
                    xtype: 'containerfield',
                    flex: 8,
                    label: 'Won',
                    labelMinWidth: 50,
                    items: [
                        {
                            xtype: 'segmentedbutton',
                            name: 'playerWon',
                            items: [
                                {
                                    xtype: 'button',
                                    name: 'playerWhite',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-user-o',
                                    text: 'White',
                                    value: 'white'
                                },
                                {
                                    xtype: 'button',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-pause',
                                    text: 'Draw',
                                    value: 'draw'
                                },
                                {
                                    xtype: 'button',
                                    name: 'playerBlack',
                                    iconAlign: 'top',
                                    iconCls: 'x-fa fa-user',
                                    text: 'Black',
                                    value: 'black'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3
                },
                {
                    xtype: 'containerfield',
                    flex: 8,
                    bodyAlign: 'center',
                    label: 'Run out of time',
                    labelMinWidth: 105,
                    items: [
                        {
                            xtype: 'segmentedbutton',
                            height: 50,
                            name: 'time',
                            width: 100,
                            value: 'false',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    pressed: true,
                                    text: 'No',
                                    value: 'false'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    text: 'Yes',
                                    value: 'true'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            platformConfig: {
                '!desktop': {
                    hidden: false
                },
                desktop: {
                    hidden: true
                }
            },
            hidden: true,
            margin: 10,
            layout: 'center',
            items: [
                {
                    xtype: 'button',
                    ui: 'confirm',
                    text: 'Add new game',
                    listeners: {
                        tap: {
                            fn: 'onAddNewGameButtonTap',
                            scope: 'controller'
                        }
                    }
                }
            ]
        }
    ],

    onMycomboboxChange: function(combobox, newValue, oldValue, eOpts) {
        this.comboChange();
    },

    onMybutton11Tap: function(button, e, eOpts) {
        const whiteCombo = this.query('combobox[name=playerWhite]')[0];
        const blackCombo = this.query('combobox[name=playerBlack]')[0];

        const whiteSelection = whiteCombo.getSelection();
        const blackSelection = blackCombo.getSelection();

        // to avoid player playing aginast each other protection
        blackCombo.setSelection('');
        whiteCombo.setSelection(blackSelection);
        blackCombo.setSelection(whiteSelection);
    },

    onMycombobox1Change: function(combobox, newValue, oldValue, eOpts) {
        this.comboChange();
    },

    comboChange: function() {
        let whiteName = this.query('combobox[name=playerWhite]')[0].getSelection();
        let blackName = this.query('combobox[name=playerBlack]')[0].getSelection();

        whiteName = whiteName ? whiteName.get('name') : "";
        blackName = blackName ? blackName.get('name') : "";


        if (whiteName == blackName && (whiteName !== "" && whiteName !== null)){
            Ext.toast('Player can\'t play againts himself', 3000);
            // <debug>
            console.log(`Players playing against each other:${whiteName} vs ${blackName}`);
            // </debug>
        }


        if(whiteName !== "") this.query('button[name=playerWhite]')[0].setText(whiteName);
        if(blackName !== "") this.query('button[name=playerBlack]')[0].setText(blackName);
    }

});