/*
 * File: app/view/mobile/MainPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    Insert the empty items to the gird to disable the toolbar
    Insert the emmpty plugins object
    Insert the emtpy selectable to save space
*/
Ext.define('Enif.view.mobile.MainPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mobile.mainpanel',

    requires: [
        'Enif.view.mobile.MainPanelViewModel',
        'Enif.view.forms.AddGameForm',
        'Enif.view.grids.GameGrid',
        'Ext.form.Panel',
        'Ext.grid.Grid'
    ],

    viewModel: {
        type: 'mobile.mainpanel'
    },
    height: '100%',
    layout: 'vbox',
    title: 'Chess Elo Rating by profiq',
    titleAlign: 'center',

    items: [
        {
            xtype: 'forms.addgameform',
            itemId: 'forms.addgameform1',
            width: '100%'
        },
        {
            xtype: 'grids.gamegrid',
            items: {
                
            },
            plugins: {
                
            },
            height: 900,
            selectable: {
                mode: 'single',
                checkbox: false
            },
            title: 'Games'
        }
    ]

});