/*
 * File: app/store/GamesData.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.GamesData', {
    extend: 'Ext.data.Store',
    alias: 'store.gamesdatas',

    requires: [
        'MyApp.model.GamesData',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'GamesData',
            autoLoad: true,
            model: 'MyApp.model.GamesData',
            proxy: {
                type: 'ajax',
                url: 'http://localhost:8181/games',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});