/*
 * File: app/view/MainPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    TODO: The routes are not working when accesing the page - possible bug in ExtJS?
*/
Ext.define('Enif.view.MainPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainpanel',

    requires: [
        'Enif.view.forms.AddGameDialog'
    ],

    onAddGameTap: function(button, e, eOpts) {
        Ext.create('Enif.view.forms.AddGameDialog').show();
    },

    onRefreshButtonTap: function(button, e, eOpts) {
        Enif.app.getController('storeLoadController').reloadAllStores();
    },

    onTabChange: function(sender, value, oldValue, eOpts) {
        if(!value.routeValue) return;
        this.redirectTo(value.routeValue);
    }

});