/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.MainPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainpanel',

    requires: [
        'Enif.view.MainPanelViewModel',
        'Enif.view.MainPanelViewController',
        'Enif.view.grids.PlayerGrids',
        'Enif.view.charts.Ladder',
        'Enif.view.charts.PlayedGames',
        'Enif.view.grids.GameGrid',
        'Enif.view.charts.EloRating',
        'Enif.view.pivot.RoundRobinGrid',
        'Enif.view.pivot.HeatMap',
        'Enif.view.charts.PlayerVsPlayer',
        'Enif.view.stats',
        'Ext.Toolbar',
        'Ext.Img',
        'Ext.Label',
        'Ext.Button',
        'Ext.Panel',
        'Ext.pivot.Grid',
        'Ext.panel.Collapser'
    ],

    controller: 'mainpanel',
    viewModel: {
        type: 'mainpanel'
    },
    height: '100%',
    id: 'mainTabPanel',
    maxWidth: '100%',
    tabBarPosition: 'left',

    items: [
        {
            xtype: 'toolbar',
            cls: 'main_toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'image',
                    height: 40,
                    width: 180,
                    margin: '0 0 0 -10',
                    src: 'https://www.profiq.com/wp-content/themes/profiq/images/logo.png'
                },
                {
                    xtype: 'label',
                    cls: 'main_text',
                    html: 'Chess ELO App'
                },
                {
                    xtype: 'button',
                    height: 35,
                    ui: 'round',
                    width: 125,
                    margin: '0 0 0 50',
                    tooltip: 'Add new game dilaog',
                    text: 'Add New Game',
                    listeners: {
                        tap: 'onAddGameTap'
                    }
                },
                {
                    xtype: 'button',
                    height: 35,
                    ui: 'round',
                    margin: '0 0 0 10',
                    tooltip: 'Refresh the data',
                    iconCls: 'x-fa fa-refresh',
                    listeners: {
                        tap: 'onRefreshButtonTap'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            iconCls: 'x-fa fa-users',
            routeValue: 'players',
            title: 'Players',
            height: '100%',
            width: 1200,
            maxWidth: 1000,
            layout: 'vbox',
            items: [
                {
                    xtype: 'panel',
                    minHeight: 420,
                    collapsible: 'top',
                    title: 'Players',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'grids.playergrids',
                            minHeight: 420
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'charts.ladder',
                            title: 'Player ELO ladder',
                            titleAlign: 'center',
                            flex: 1
                        },
                        {
                            xtype: 'charts.playedgames',
                            flex: 1
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            routeValue: 'games',
            iconCls: 'x-fa fa-trophy',
            title: 'Games',
            cls: 'grid_background_image',
            items: [
                {
                    xtype: 'grids.gamegrid',
                    iconCls: 'x-fa fa-trophy',
                    routeValue: 'games',
                    style: 'opacity: 0.95',
                    title: 'Games'
                }
            ]
        },
        {
            xtype: 'charts.elorating',
            iconCls: 'x-fa fa-line-chart',
            routeValue: 'eloChart',
            title: 'Elo Rating Chart'
        },
        {
            xtype: 'container',
            routeValue: 'roundRobin',
            iconCls: 'x-fa fa-table',
            title: 'Round Robin',
            items: [
                {
                    xtype: 'pivot.roundrobingrid'
                }
            ]
        },
        {
            xtype: 'pivot.heatmap',
            routeValue: 'heatMap',
            iconCls: 'x-fa fa-th',
            title: 'Heat Map'
        },
        {
            xtype: 'charts.playervsplayer',
            routeValue: 'playerScore',
            iconCls: 'x-fa fa-area-chart',
            title: 'Player Score'
        },
        {
            xtype: 'stats',
            iconCls: 'x-fa fa-pie-chart',
            title: 'Stats'
        }
    ],
    listeners: {
        activeItemchange: 'onTabChange'
    }

});