/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    We need data from Person store for calculation in the views, load store before loading views and other stores
*/
Ext.define('Enif.view.MainViewport', {
    extend: 'Ext.Container',
    alias: 'widget.mainviewport',

    requires: [
        'Enif.view.MainViewportViewModel',
        'Enif.view.MainViewportViewController',
        'Enif.view.Loading',
        'Ext.Container'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    height: '100%',
    width: '100%',

    items: [
        {
            xtype: 'loading',
            reference: 'loading'
        }
    ],
    listeners: {
        initialize: 'onMainContainerInitialize'
    }

});