/*
 * File: app/view/stats.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.stats', {
    extend: 'Ext.Panel',
    alias: 'widget.stats',

    requires: [
        'Enif.view.statsViewModel',
        'Enif.view.charts.WinsByColor',
        'Enif.view.charts.PlayedGames',
        'Ext.Panel'
    ],

    viewModel: {
        type: 'stats'
    },
    height: '100%',
    layout: 'hbox',
    title: 'Chart Stats',

    items: [
        {
            xtype: 'charts.winsbycolor',
            flex: 1
        },
        {
            xtype: 'charts.playedgames',
            flex: 1
        }
    ]

});