/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'MyApp.view.MyTabPanelViewModel',
        'MyApp.view.grid.PlayerGrid',
        'MyApp.view.grid.GamesGrid',
        'MyApp.view.chart.EloRating',
        'Ext.grid.Grid',
        'Ext.Toolbar'
    ],

    viewModel: {
        type: 'mytabpanel'
    },
    tabBarPosition: 'left',

    items: [
        {
            xtype: 'grid.playergrid',
            title: 'Players',
            iconCls: 'x-fa fa-users'
        },
        {
            xtype: 'grid.gamesgrid',
            title: 'Games',
            iconCls: 'x-fa fa-trophy'
        },
        {
            xtype: 'chart.elorating',
            title: 'Elo Rating Chart',
            iconCls: 'x-fa fa-line-chart '
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            title: 'Our Elo Rating App'
        }
    ]

});