/*
 * File: app/model/GamesData.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.model.GamesData', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],


    idProperty: 'uid',
    fields: [
        {
            type: 'int',
            name: 'timestamp'
        },
        {
            type: 'int',
            name: 'playerWhite'
        },
        {
            type: 'float',
            name: 'playerWhiteRating'
        },
        {
            type: 'int',
            name: 'playerBlack'
        },
        {
            type: 'float',
            name: 'playerBlackRating'
        },
        {
            type: 'string',
            name: 'result'
        },
        {
            type: 'boolean',
            name: 'timeout'
        },
        {
            name: 'id',
            persist: false
        },
        {
            name: 'uid'
        }
    ],
    validators: [
        {
            type: 'presence',
            field: 'playerWhite'
        },
        {
            type: 'presence',
            field: 'playerBlack'
        }
    ]

});