/*
 * File: app/model/GamesData.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.GamesData', {
    extend: 'Ext.data.Model',
    alias: 'model.gamesdata',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],


    fields: [
        {
            type: 'int',
            name: 'timestamp'
        },
        {
            type: 'int',
            name: 'playerWhite'
        },
        {
            type: 'int',
            name: 'playerBlack'
        },
        {
            type: 'string',
            name: 'result'
        },
        {
            type: 'boolean',
            name: 'timeout'
        },
        {
            type: 'int',
            name: 'playerWhiteRating'
        },
        {
            type: 'int',
            name: 'playerBlackRating'
        },
        {
            type: 'int',
            name: 'uid'
        }
    ]

});