/*
 * File: app/view/charts/EloRatingViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.charts.EloRatingViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.charts.elorating',

    data: {
        axes: [
            {
                type: 'category',
                renderer: function(axis, label, layoutContext, lastLabel) {
                                    return Ext.Date.format(new Date(label), 'd.m.y');
                                },
                fields: [
                    'timestamp'
                ],
                title: 'Dates'
            },
            {
                type: 'numeric',
                fields: [
                    'player0Rating',
                    'player1Rating',
                    'player2Rating',
                    'player3Rating',
                    'player4Rating',
                    'player5Rating',
                    'player6Rating',
                    'player7Rating',
                    'player8Rating'
                ],
                grid: {
                    odd: {
                        line: '#e8e8e8'
                    }
                },
                margin: 10,
                position: 'right',
                title: 'Elo rating'
            }
        ]
    }

});