/*
 * File: app/view/charts/EloRatingNavigator.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    Series for this chart are generated in the ViewController dynamicall
    Don't forget to add series to the requires (needed for the production build)
    FYI: The data are dynamic - not shown inside SA canvas
*/
Ext.define('Enif.view.charts.EloRatingNavigator', {
    extend: 'Ext.Container',
    alias: 'widget.charts.eloratingnavigator',

    requires: [
        'Enif.view.charts.EloRatingViewModel1',
        'Enif.view.charts.EloRatingViewController1',
        'Ext.Toolbar',
        'Ext.SegmentedButton',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.chart.navigator.Container',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.legend.Legend',
        'Ext.chart.interactions.ItemInfo',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.interactions.CrossZoom',
        'Ext.chart.navigator.Navigator',
        'Ext.chart.series.Line'
    ],

    controller: 'charts.eloratingnavigator',
    viewModel: {
        type: 'charts.eloratingnavigator'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'toolbar',
            reference: 'toolbar',
            docked: 'top',
            layout: {
                type: 'hbox',
                align: 'end'
            },
            items: [
                {
                    xtype: 'segmentedbutton',
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            text: 'Cross Zoom',
                            listeners: {
                                tap: 'onEnableCrossZoomButtonTap'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            pressed: true,
                            text: 'Pan Zoom',
                            listeners: {
                                tap: 'onEnablePanZoomButtonTap'
                            }
                        }
                    ]
                },
                {
                    xtype: 'spacer',
                    width: 40
                },
                {
                    xtype: 'button',
                    reference: 'resetCrossZoom',
                    disabled: true,
                    ui: 'action',
                    text: 'Reset Zoom',
                    listeners: {
                        tap: 'onZoomResetButtonTap'
                    }
                }
            ]
        },
        {
            xtype: 'chartnavigator',
            chart: {
                xtype: 'cartesian',
                reference: 'chart',
                itemId: 'mylinechart',
                margin: 25,
                padding: 20,
                colors: [
                    '#115fa6',
                    '#94ae0a',
                    '#a61120',
                    '#ff8809',
                    '#ffd13e',
                    '#a61187',
                    '#24ad9a',
                    '#7c7474',
                    '#a66111'
                ],
                store: 'EloRatinChart',
                innerPadding: {
                    top: 10,
                    left: 10,
                    right: 10,
                    bottom: 10
                },
                axes: [
                    {
                        type: 'category',
                        renderer: function(axis, label, layoutContext, lastLabel) {
                            return Ext.Date.format(new Date(label), 'd.m.y');
                        },
                        fields: [
                            'timestamp'
                        ],
                        id: 'categoryAxis',
                        title: 'Dates'
                    },
                    {
                        type: 'numeric',
                        fields: [
                            'player0Rating',
                            'player1Rating',
                            'player2Rating',
                            'player3Rating',
                            'player4Rating',
                            'player5Rating',
                            'player6Rating',
                            'player7Rating',
                            'player8Rating'
                        ],
                        grid: {
                            odd: {
                                line: '#e8e8e8'
                            }
                        },
                        id: 'eloAxis',
                        margin: 10,
                        position: 'right',
                        title: 'Elo rating'
                    }
                ],
                legend: {
                    xtype: 'legend',
                    docked: 'right'
                },
                interactions: [
                    {
                        type: 'iteminfo',
                        enabled: false
                    },
                    {
                        type: 'panzoom',
                        modeToggleButton: {
                            width: 200,
                            defaults: {
                                flex: 1,
                                ui: 'action'
                            },
                            reference: 'panZoomToggle',
                            items: [
                                {
                                    iconCls: 'x-fa fa-arrows',
                                    text: 'Pan',
                                    value: 'pan'
                                },
                                {
                                    iconCls: 'x-fa fa-search-plus',
                                    text: 'Zoom',
                                    value: 'zoom'
                                }
                            ]
                        },
                        axes: {
                            left: {
                                allowPan: false,
                                allowZoom: false
                            }
                        }
                    },
                    {
                        type: 'crosszoom',
                        enabled: false
                    }
                ]
            },
            navigator: {
                colors: [
                    '#115fa6',
                    '#94ae0a',
                    '#a61120',
                    '#ff8809',
                    '#ffd13e',
                    '#a61187',
                    '#24ad9a',
                    '#7c7474',
                    '#a66111'
                ],
                axis: 'categoryAxis'
            }
        }
    ],
    listeners: {
        initialize: 'onContainerInitialize'
    }

});