/*
 * File: app/view/charts/PlayedGames.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enif.view.charts.PlayedGames', {
    extend: 'Ext.Panel',
    alias: 'widget.charts.playedgames',

    requires: [
        'Enif.view.charts.PlayedGamesViewModel',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie',
        'Ext.chart.interactions.Rotate',
        'Ext.chart.legend.Legend',
        'Ext.chart.interactions.ItemHighlight'
    ],

    viewModel: {
        type: 'charts.playedgames'
    },
    title: 'Number of games',
    titleAlign: 'center',

    items: [
        {
            xtype: 'polar',
            height: '100%',
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            store: 'PlayerData',
            series: [
                {
                    type: 'pie',
                    highlightCfg: {
                        margin: 20
                    },
                    label: {
                        field: 'name',
                        display: 'rotate',
                        font: '14px Arial'
                    },
                    style: {
                        stroke: 'white',
                        miterLimit: 10,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    angleField: 'games',
                    donut: 30
                }
            ],
            interactions: [
                {
                    type: 'rotate'
                },
                {
                    type: 'itemhighlight'
                }
            ],
            legend: {
                xtype: 'legend',
                axisLock: false,
                docked: 'left',
                layout: 'center'
            }
        }
    ]

});